application: on-golang
version: 1
runtime: go
api_version: go1

handlers:
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
- url: /tweet
  script: _go_app
  login: admin
- url: /.*
  script: _go_app

nobuild_files: ^(support|content)/
